#!/bin/bash  

# The source directory of the backgrounds
SOURCE_DIR="$HOME/pictures/wallpapers"
# taking the chance to process any new additions
BLUR_DIR="$HOME/pictures/wallpapers-processed"
blur-wallpapers

wallpaper="$SOURCE_DIR/$1"
blurpaper="$BLUR_DIR/$1"

# Exit if no wallpaper is selected
if [ -z "$wallpaper" ]; then
  echo "no wallpaper selected."
  exit 1
fi

# Kill the current swaybg instance, and start another
pkill -x swaybg
case "$WALLPAPER_BACKEND" in
  awww)
    awww img "$blurpaper" --transition-type fade
    ;;
  swaybg)
    swaybg -i "$blurpaper" -m fill > /dev/null 2>&1 &
    ;;
esac
ln -sf "$blurpaper" "$HOME/.local/share/current_wallpaper.jpg"

# use wallust to generate colour pallet and update
echo "$wallpaper"
# Run wallust on the selected wallpaper
# wallust run -q "$wallpaper"
wallust run "$wallpaper"
# Send SIGUSR1 to dwl
pkill -USR1 -x dwl
# send signal to mako
makoctl reload
